export const AFFIRMATIONS: string[] = [
  'You are deeply loved by those around you.',
  'Every day is a new opportunity to enjoy life.',
  'You have a lifetime of wisdom and experience.',
  'You matter, and your presence brings joy to others.',
  'Today is a good day to appreciate the little things.',
  'You are stronger than you know.',
  'The people who love you are always with you in spirit.',
  'You have touched many lives in beautiful ways.',
  'Each moment is a gift — embrace it with peace.',
  'You are safe, you are cared for, you are loved.',
  'Your smile lights up every room you walk into.',
  'The memories you carry are a treasure.',
  'You are never alone — love surrounds you always.',
  'Today holds something beautiful, just for you.',
  'Your story is one worth celebrating.',
  'You bring warmth and joy to everyone you meet.',
  'One step at a time — you are doing wonderfully.',
  'You are cherished more than words can say.',
  'Breathe deeply. You are exactly where you need to be.',
  'Your kindness has made the world a better place.',
  'You have so much to be proud of.',
  'Good things are all around you today.',
  'Your family loves you with their whole hearts.',
  'You are brave, and you are beautiful.',
  'Every day with you is a blessing to your loved ones.',
  'You deserve peace, comfort, and happiness.',
  'The best is yet to come.',
  'You have lived a life full of meaning and love.',
  'You are wonderful, exactly as you are.',
  'Today, choose joy — it is always within reach.',
];
